version: '3'

services:

  eureka-server:
    build:
      context: ./Eureka-Server
    ports:
      - "8761:8761"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carservicedb
    ports:
      - "3307:3306"

  service-client:
    build:
      context: ./Client
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientservicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  gateway:
    build:
      context: ./Gatway
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  service-car:
    build:
      context: ./Voiture
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carservicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
